# Generated by Django 4.0.6 on 2022-07-15 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Please input first name', max_length=50)),
                ('last_name', models.CharField(default='Please input last name', max_length=50)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('user_id', models.CharField(default='Please input user name', max_length=50)),
                ('password', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('nationality', models.CharField(default='please input nationality', max_length=100)),
                ('photo_url', models.ImageField(default='please upload your profile image', upload_to='profile')),
                ('address', models.CharField(max_length=250)),
                ('lat', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default="Emergency! I'm in danger now, please help me!")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to='captain_citizen.user')),
            ],
        ),
    ]
